### ISSUE TITLE
Is there a ros2 branch?

### ISSUE THREAD

**Issue by narutojxl** [xqms/rosbag_fancy#15]
Hello, 
It looks cool, is there a ros2 branch? Thanks a lot!

**Comment by xqms** [comment]
Thanks :) No, unfortunately there is no ROS2 support yet. I'm not using ROS2 yet and I'm not planning to do so until end of this year. But there is some discussion on the subject here: https://github.com/ros2/rosbag2/issues/682

**Comment by narutojxl** [comment]
Thanks author.
