### ISSUE TITLE
cannot record bag when /use_sim_time is true

### ISSUE THREAD

**Issue by plusk01** [xqms/rosbag_fancy#16]
I have set `/use_sim_time` as `true`. i am playing another rosbag and then recording the output of an algorithm. I start the other bag with `rosbag play my.bag --clock --pause`. Note that after starting the bag (and before unpausing), the `ros::Time::now()` call should return a non-zero value, e.g.,:

```python
In [1]: import rospy

In [2]: rospy.init_node('anon')

In [3]: rospy.Time.now()
Out[3]: rospy.Time[1357847237249109029]
```

however, trying to record a bag i see

```bash
$ rosrun rosbag_fancy rosbag_fancy record /odom
[ INFO] [1651258063.201820822]: Opening bag file: bag_1969-12-31-19-00-00.bag
[ERROR] [1651258063.202937185]: Could not open output bag file: Tried to insert a message with time less than ros::TIME_MIN
```

so maybe something in `rosbag_fancy` is uninitialized?

**Comment by xqms** [comment]
Thanks for the report! Indeed, we have to wait until `ros::Time` is initialized in this case. I just pushed a fix to `master`. If you are able to build from source, I'd appreciate if you could confirm it fixes your isse :)

**Comment by plusk01** [comment]
this fixed it for me, thanks

fyi, the bag saves as `bag_2013-01-10-14-47-17.bag` (i.e., the bag's `--clock` time). This is fine for me, but some users may expect it to save with the current timestamp, not the simulated one. Not sure anything needs to be done at this point, but just wanted to document it
