### ISSUE TITLE
dynamic_reconfigure for per-topic rate limiting 

### ISSUE THREAD

**Issue by garyedwards** [xqms/rosbag_fancy#22]
Hi, this is related to https://github.com/xqms/rosbag_fancy/issues/21 for a data capture vehicle.

We would like to rate limit recording of topics based on the current velocity of a vehicle.  Would it be possible to expose per-topic rate limiting as parameters and have these update at runtime without having to restart the node using dynamic_reconfigure for example?

**Comment by xqms** [comment]
Hmm, I would think it would be easier to implement rate limiting on your side (or add an intermediate throttling node) rather than having to use dynamic reconfigure for this purpose. That said, I would welcome a PR that adds this functionality.

**Comment by garyedwards** [comment]
Hi, I will review our drivers and triggering design, as you say it may fit better at that level or an intermediate node.  If we do end up back at the record level I will work up a PR if we get something working well.
