### ISSUE TITLE
catkin_make error 

### ISSUE THREAD

**Issue by TranquilityOcean** [xqms/rosbag_fancy#8]
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindCurses.cmake:245 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  rosbag_fancy/CMakeLists.txt:17 (find_package)

**Comment by xqms** [comment]
You need to install the dependencies of the package...

You can do that either using `rosdep install --from-path .` when inside the package, or directly using `sudo apt install libncurses-dev`.

**Comment by xqms** [comment]
I'm assuming your error is fixed by my comment above, if not, feel free to reopen this issue / open a more specific issue.
